import "./globals.css";

import { Footer } from "@ui/molecules";
import { Header } from "@ui/organisms";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header cartAmount={10} />
        <section className="page">{children}</section>
        <Footer />
      </body>
    </html>
  );
}
