import "./globals.css";

import { AppProvider } from "@store/provider";
import { Footer } from "@ui/molecules";
import { Header } from "@ui/organisms";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body>
        <AppProvider>
          <Header />
          <section className="page">{children}</section>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
